"""Generate backend/tests/fixtures/asr_{en,hi,hinglish}.json from the fixture scripts.

These are SYNTHETIC: word timings come from a seeded RNG, not from real speech. They exist to test
segmentation and feature logic on faster-whisper-shaped input. Real-audio behaviour is covered only
by the opt-in GPU test (pytest -m gpu) with team-recorded clips.

Deterministic: re-running produces byte-identical files.
    python scripts/make_asr_fixtures.py
"""

import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from backend.app.transcription.script_timing import parse_script  # noqa: E402

FIX = ROOT / "backend" / "tests" / "fixtures"
PUNCT = ".,?!।;:"

# Per-language quirks being exercised:
#  en       — 18 s music-only intro before the first word (silence segment / slow-hook evidence)
#  hi       — Devanagari with danda; a 7 s silent demo after paragraph 7
#  hinglish — paragraphs 5–6 have no punctuation at all (pause-fallback sentence splitting)
SPECS = {
    "en": {"seed": 11, "lead_s": 18.0, "silence_after": {}, "strip_punct": set(), "tail_s": 2.0},
    "hi": {
        "seed": 22,
        "lead_s": 0.4,
        "silence_after": {7: 7.0},
        "strip_punct": set(),
        "tail_s": 1.5,
    },
    "hinglish": {
        "seed": 33,
        "lead_s": 0.6,
        "silence_after": {},
        "strip_punct": {5, 6},
        "tail_s": 1.0,
    },
}


def build(lang: str) -> dict:
    spec = SPECS[lang]
    rng = random.Random(spec["seed"])
    paragraphs = parse_script((FIX / f"{lang}_script.txt").read_text(encoding="utf-8"))
    words = []
    t = spec["lead_s"]
    for p_idx, para in enumerate(paragraphs):
        strip = p_idx in spec["strip_punct"]
        for k, tok in enumerate(para):
            text = tok.strip(PUNCT) if strip and k < len(para) - 1 else tok
            if strip and k == len(para) - 1:
                text = tok.rstrip(PUNCT)
            dur = rng.uniform(0.22, 0.5)
            words.append(
                {
                    "word": " " + text,
                    "start": round(t, 2),
                    "end": round(t + dur, 2),
                    "probability": round(rng.uniform(0.80, 0.99), 3),
                }
            )
            t += dur
            last = k == len(para) - 1
            if last:
                t += rng.uniform(0.8, 1.4) + spec["silence_after"].get(p_idx, 0.0)
            elif not strip and tok[-1] in ".?!।":
                t += rng.uniform(0.3, 0.55)
            elif strip and rng.random() < 0.12:
                t += rng.uniform(0.65, 1.0)  # natural breath pause, no punctuation
            else:
                t += rng.uniform(0.02, 0.12)
    duration = round(words[-1]["end"] + spec["tail_s"], 2)

    # group into Whisper-like segments: sentence ends or every 25 words
    segments, cur = [], []
    for w in words:
        cur.append(w)
        if w["word"].strip()[-1] in ".?!।" or len(cur) >= 25:
            segments.append(cur)
            cur = []
    if cur:
        segments.append(cur)
    return {
        "_note": "SYNTHETIC fixture generated by scripts/make_asr_fixtures.py; not real ASR output",
        "language": "hi" if lang != "en" else "en",
        "language_probability": 0.97 if lang != "hinglish" else 0.71,
        "duration": duration,
        "segments": [
            {
                "start": s[0]["start"],
                "end": s[-1]["end"],
                "text": "".join(w["word"] for w in s),
                "words": s,
            }
            for s in segments
        ],
    }


def main() -> None:
    for lang in SPECS:
        out = FIX / f"asr_{lang}.json"
        out.write_text(
            json.dumps(build(lang), ensure_ascii=False, indent=1) + "\n", encoding="utf-8"
        )
        print("wrote", out.relative_to(ROOT))


if __name__ == "__main__":
    main()
